# Generated by Django 5.1.2 on 2026-03-09 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_permalink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
