# Generated by Django 6.0.1 on 2026-03-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_newsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.AddField(
            model_name='page',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
